base:
    characters:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
    data_dir: ./data/captcha_images_v1
    downsample_factor: 4
    image_height: 50
    image_width: 200
    max_length: 4
    model_dir: ./saved_model/my_model
